# Generated by Django 3.2.12 on 2023-02-10 20:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_name', models.CharField(blank=True, max_length=20, verbose_name='Национальное название клуба')),
                ('eng_name', models.CharField(blank=True, max_length=30, verbose_name='Английское название клуба')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
                ('schools', models.JSONField(blank=True, null=True, verbose_name='Школы')),
                ('school_ages', models.TextField(blank=True, choices=[('3-4', '3-4'), ('5-6', '5-6'), ('7-8', '7-8'), ('9-10', '9-10'), ('11-12', '11-12'), ('13-14', '13-14')], default='Возрастная группа', verbose_name='Возрастная группа школы')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.TextField(blank=True, choices=[('R', 'Правая'), ('L', 'Левая'), ('B', 'Обе')], null=True, verbose_name='Нога')),
                ('position', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Вратарь'), ('2', 'Центральный защитник'), ('3', 'Левый защитник'), ('4', 'Правый защитник'), ('5', 'Центральный опорный полузащитник'), ('6', 'Центральный полузащитник'), ('7', 'Левый полузащитник'), ('8', 'Правый полузащитник'), ('9', 'Центральный нападающий'), ('10', 'Правый вингер'), ('11', 'Левый вингер'), ('12', 'Инсайдер')], max_length=26, null=True, verbose_name='Позиция')),
                ('age', models.CharField(blank=True, max_length=5, null=True, verbose_name='Возраст')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('height', models.CharField(blank=True, max_length=4, null=True, verbose_name='Рост')),
                ('weight', models.CharField(blank=True, max_length=4, null=True, verbose_name='Вес')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('shengen', models.BooleanField(blank=True, default=False, null=True, verbose_name='Шенген')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('description', models.TextField(blank=True, max_length=254, null=True, verbose_name='Описание')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=150, null=True, upload_to='video/videos', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('school', models.TextField(blank=True, max_length=250, verbose_name='Школы(Название, страна, город)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер Телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=40, null=True, verbose_name='Страна')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='Отображать_всем')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photoes', verbose_name='Фото в профиле')),
                ('country_s', models.CharField(blank=True, max_length=50, verbose_name='Страна, в которой находится школа')),
                ('city_s', models.CharField(blank=True, max_length=50, verbose_name='Город, в котором находится школа')),
                ('phone_s', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона школы')),
                ('e_mail_s', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail школы')),
                ('photo_s', models.ImageField(blank=True, null=True, upload_to='school_photoes', verbose_name='Фото школы')),
                ('players', models.ManyToManyField(blank=True, related_name='trainer_players', to='API.Player', verbose_name='Игроки тренера')),
            ],
        ),
    ]
