# Generated by Django 3.2.3 on 2023-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('player', 'Игрок'), ('agent', 'Агент'), ('club', 'Клуб'), ('parent', 'Родитель'), ('trainer', 'Тренер'), ('scout', 'Скаут')], default='player', max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
