# Generated by Django 3.2.12 on 2023-02-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
