# Generated by Django 4.0.6 on 2022-12-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.TextField(choices=[('1', 'Игрок'), ('2', 'Агент'), ('3', 'Тренер'), ('4', 'Родитель'), ('5', 'Клуб'), ('6', 'Скаут')], default=1, verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
