# Generated by Django 4.0.6 on 2022-12-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_usermodel_username_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.CharField(default=1, max_length=5, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(default=1, max_length=40, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(default=1, max_length=40, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(default=1, max_length=254, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=1, max_length=25, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='height',
            field=models.CharField(default=1, max_length=4, verbose_name='Рост'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='Отображать_всем'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='patroniymc',
            field=models.CharField(default=1, max_length=30, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default=1, max_length=30, verbose_name='Номер_Телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='shengen',
            field=models.BooleanField(default=False, verbose_name='Шенген'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sources',
            field=models.CharField(default=1, max_length=254, verbose_name='Ресурсы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='subscribe',
            field=models.TextField(choices=[('5$', 'default'), ('10$', 'spesial')], default=1, verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='video',
            field=models.FileField(default=1, upload_to='', verbose_name='Видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='weight',
            field=models.CharField(default=1, max_length=4, verbose_name='Вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('1', 'Игрок'), ('2', 'Агент'), ('3', 'Тренер'), ('4', 'Родитель'), ('5', 'Клуб'), ('6', 'Скаут')], max_length=15, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.TextField(choices=[('R', 'Правая'), ('L', 'Левая')], verbose_name='Нога')),
                ('position', models.TextField(choices=[('1', 'Вратарь'), ('2', 'Центральный защитник'), ('3', 'Левый и правый защитник'), ('4', 'Левый и правый фланговый защитник'), ('5', 'Лентральный опорный полузащитник'), ('6', 'Центральный полузащитник'), ('7', 'Левый/правый полузащитник'), ('8', 'Центральный атакующий полузащитник')], default='Позиция', verbose_name='Позиция')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.usermodel')),
            ],
        ),
    ]
