# Generated by Django 4.0.6 on 2022-12-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_usermodel_age_usermodel_city_usermodel_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
    ]
