# Generated by Django 4.0.6 on 2022-12-29 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='video',
            field=models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wav'])], verbose_name='Видео'),
        ),
    ]
