# Generated by Django 4.0.6 on 2022-12-30 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_usermodel_video_player_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='video',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='video',
            field=models.FileField(default=1, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wav'])], verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
