# Generated by Django 4.0.6 on 2022-12-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_player_video_usermodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='video',
        ),
        migrations.AddField(
            model_name='player',
            name='video',
            field=models.FileField(null=True, upload_to='video/', verbose_name='Видео'),
        ),
    ]
