# Generated by Django 4.0.6 on 2023-01-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_usermodel_video_player_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('file', models.FileField(null=True, upload_to='video/', verbose_name='Файл')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.player')),
            ],
        ),
    ]
