# Generated by Django 4.0.6 on 2023-01-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_player_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
