# Generated by Django 4.0.6 on 2023-01-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='video/photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Превью'),
        ),
    ]
