# Generated by Django 4.0.6 on 2023-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='players',
            field=models.JSONField(blank=True, verbose_name='Игроки'),
        ),
    ]
