# Generated by Django 4.0.6 on 2023-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_agent_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='passport',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
