# Generated by Django 4.0.6 on 2023-01-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_agent_passport_alter_usermodel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Превью'),
        ),
    ]
