# Generated by Django 4.0.6 on 2023-01-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='videos/photo/', verbose_name='Превью'),
        ),
    ]
