# Generated by Django 4.0.6 on 2023-01-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronimyc', models.CharField(max_length=30, verbose_name='Отчество')),
                ('passport', models.ImageField(blank=True, upload_to='documents/', verbose_name='Фото паспорта')),
                ('players', models.JSONField(blank=True, null=True, verbose_name='Игроки')),
            ],
        ),
    ]
