# Generated by Django 4.0.6 on 2023-01-04 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronimyc', models.CharField(max_length=30, verbose_name='Отчество')),
                ('passport', models.ImageField(blank=True, upload_to='documents/', verbose_name='Фото паспорта')),
                ('players', models.JSONField(blank=True, null=True, verbose_name='Игроки')),
                ('country_s', models.CharField(max_length=50, verbose_name='Страна, в которой находится школа')),
                ('city_s', models.CharField(max_length=50, verbose_name='Город, в котором находится школа')),
                ('phone_s', models.CharField(max_length=15, verbose_name='Номер телефона школы')),
                ('e_mail_s', models.EmailField(max_length=254, verbose_name='E-Mail школы')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photo/', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.trainer')),
            ],
        ),
    ]
