# Generated by Django 3.2.12 on 2023-01-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20230104_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoSchool',
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photoes/', verbose_name='фото в профиле'),
        ),
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photoes/', verbose_name='фото в профиле'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_photoes/', verbose_name='фото в профиле'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photoes/', verbose_name='Фото в профиле'),
        ),
    ]
