# Generated by Django 3.2.12 on 2023-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20230104_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='patroniymc',
            new_name='patronimyc',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='second_name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
