# Generated by Django 3.2.12 on 2023-01-09 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0026_auto_20230105_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.CharField(max_length=5, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=40, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(max_length=40, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(max_length=254, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='height',
            field=models.CharField(max_length=4, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_show',
            field=models.BooleanField(default=True, null=True, verbose_name='Отображать_всем'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='patronimyc',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Номер Телефона'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('1', 'Игрок'), ('2', 'Агент'), ('3', 'Тренер'), ('4', 'Родитель'), ('5', 'Клуб'), ('6', 'Скаут')], max_length=15, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='second_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='shengen',
            field=models.BooleanField(default=False, null=True, verbose_name='Шенген'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sources',
            field=models.CharField(max_length=254, null=True, verbose_name='Ресурсы'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subscribe',
            field=models.TextField(choices=[('5$', 'default'), ('10$', 'spesial')], null=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='weight',
            field=models.CharField(max_length=4, null=True, verbose_name='Вес'),
        ),
    ]
