# Generated by Django 3.2.12 on 2023-01-10 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0028_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.CharField(blank=True, default=1, max_length=5, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='description',
            field=models.TextField(blank=True, default=1, max_length=254, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=100, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='height',
            field=models.CharField(blank=True, default=1, max_length=4, verbose_name='Рост'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_show',
            field=models.BooleanField(blank=True, default=True, verbose_name='Отображать_всем'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='patronimyc',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Номер Телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Игрок'), ('2', 'Агент'), ('3', 'Тренер'), ('4', 'Родитель'), ('5', 'Клуб'), ('6', 'Скаут')], default=1, max_length=15, verbose_name='Роль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='second_name',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='shengen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Шенген'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sources',
            field=models.CharField(blank=True, default=1, max_length=254, verbose_name='Ресурсы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subscribe',
            field=models.TextField(blank=True, choices=[('5$', 'default'), ('10$', 'spesial')], default=1, verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='weight',
            field=models.CharField(blank=True, default=1, max_length=4, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
