# Generated by Django 3.2.12 on 2023-01-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20230110_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='first_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='passport',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Фото паспорта'),
        ),
        migrations.AddField(
            model_name='club',
            name='patronimyc',
            field=models.CharField(default=1, max_length=30, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.JSONField(blank=True, null=True, verbose_name='Игроки'),
        ),
        migrations.AddField(
            model_name='club',
            name='school_ages',
            field=models.TextField(choices=[('3-4', '3-4'), ('5-6', '5-6'), ('7-8', '7-8'), ('9-10', '9-10'), ('11-12', '11-12'), ('13-14', '13-14')], default='Возрастная группа', verbose_name='Возрастная группа школы'),
        ),
        migrations.AddField(
            model_name='club',
            name='schools',
            field=models.JSONField(blank=True, null=True, verbose_name='Школы'),
        ),
        migrations.AddField(
            model_name='club',
            name='second_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronimyc', models.CharField(max_length=30, verbose_name='Отчество')),
                ('passport', models.ImageField(blank=True, upload_to='documents/', verbose_name='Фото паспорта')),
                ('school', models.TextField(max_length=250, verbose_name='Школы(Название, страна, город)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.usermodel')),
            ],
        ),
    ]
